# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#


#version: 2.1

executors:
  shopizer-ci:
    docker:
      - image: shopizerecomm/ci:latest
        auth:
          username: shopizerecomm
          password: $DOCKERHUB_PASSWORD  


#working_directory: ~/shopizer

version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "shopizer build and test (1)"
      - run:
          name: Run shell script
          command: |
            set -x
            /home/shopizer/tools/shopizer.sh tests
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run: |
          docker build . -t shopizerecomm/shopizer:latest
          docker login -u shopizerecomm -p $DOCKERHUB_PASSWORD


# Orchestrate our job run sequence
workflows:
  build_and_test_and_depploy:
    jobs:
      - build

#jobs:
#  build:
#    steps:
#      - checkout
#      - run: echo "this is the build job"
#  test:
    #executor: shopizer-ci
#    steps:
#      - checkout
#      - run: echo "this is the test job"
      #- run: shopizer tests



#workflows:
#  build_and_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build