# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#


version: 2.1

executors:
  shopizer-ci:
    docker:
      - image: shopizerecomm/ci:latest
        auth:
          username: shopizerecomm
          password: $DOCKERHUB_PASSWORD  


working_directory: ~/shopizer



jobs:
  build:
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: shopizer tests



workflows:
  build_and_test:
    jobs:
      - build
      - test
          requires:
            - build